{% set name = "perl-variable-magic" %}
{% set version = "0.64" %}
{% set sha256 = "9f7853249c9ea3b4df92fb6b790c03a60680fc029f44c8bf9894dccf019516bd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/V/VP/VPIT/Variable-Magic-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Variable::Magic

about:
  home: http://search.cpan.org/dist/Variable-Magic/
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'Associate user-defined magic to variables from Perl.'

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
